// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/resiliency/resiliency.proto

package resiliency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ResiliencyService_UnaryResiliency_FullMethodName               = "/resiliency.ResiliencyService/UnaryResiliency"
	ResiliencyService_ServerStreamResiliency_FullMethodName        = "/resiliency.ResiliencyService/ServerStreamResiliency"
	ResiliencyService_ClientStreamResiliency_FullMethodName        = "/resiliency.ResiliencyService/ClientStreamResiliency"
	ResiliencyService_BidirectionalStreamResiliency_FullMethodName = "/resiliency.ResiliencyService/BidirectionalStreamResiliency"
)

// ResiliencyServiceClient is the client API for ResiliencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// status gRPC vai ser um dos status code listados na request
type ResiliencyServiceClient interface {
	UnaryResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyReponse, error)
	ServerStreamResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyService_ServerStreamResiliencyClient, error)
	ClientStreamResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_ClientStreamResiliencyClient, error)
	BidirectionalStreamResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_BidirectionalStreamResiliencyClient, error)
}

type resiliencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResiliencyServiceClient(cc grpc.ClientConnInterface) ResiliencyServiceClient {
	return &resiliencyServiceClient{cc}
}

func (c *resiliencyServiceClient) UnaryResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResiliencyReponse)
	err := c.cc.Invoke(ctx, ResiliencyService_UnaryResiliency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiliencyServiceClient) ServerStreamResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyService_ServerStreamResiliencyClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[0], ResiliencyService_ServerStreamResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceServerStreamResiliencyClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResiliencyService_ServerStreamResiliencyClient interface {
	Recv() (*ResiliencyReponse, error)
	grpc.ClientStream
}

type resiliencyServiceServerStreamResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceServerStreamResiliencyClient) Recv() (*ResiliencyReponse, error) {
	m := new(ResiliencyReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyServiceClient) ClientStreamResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_ClientStreamResiliencyClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[1], ResiliencyService_ClientStreamResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceClientStreamResiliencyClient{ClientStream: stream}
	return x, nil
}

type ResiliencyService_ClientStreamResiliencyClient interface {
	Send(*ResiliencyRequest) error
	CloseAndRecv() (*ResiliencyReponse, error)
	grpc.ClientStream
}

type resiliencyServiceClientStreamResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceClientStreamResiliencyClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyServiceClientStreamResiliencyClient) CloseAndRecv() (*ResiliencyReponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResiliencyReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyServiceClient) BidirectionalStreamResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_BidirectionalStreamResiliencyClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[2], ResiliencyService_BidirectionalStreamResiliency_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceBidirectionalStreamResiliencyClient{ClientStream: stream}
	return x, nil
}

type ResiliencyService_BidirectionalStreamResiliencyClient interface {
	Send(*ResiliencyRequest) error
	Recv() (*ResiliencyReponse, error)
	grpc.ClientStream
}

type resiliencyServiceBidirectionalStreamResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceBidirectionalStreamResiliencyClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyServiceBidirectionalStreamResiliencyClient) Recv() (*ResiliencyReponse, error) {
	m := new(ResiliencyReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyServiceServer is the server API for ResiliencyService service.
// All implementations must embed UnimplementedResiliencyServiceServer
// for forward compatibility
//
// status gRPC vai ser um dos status code listados na request
type ResiliencyServiceServer interface {
	UnaryResiliency(context.Context, *ResiliencyRequest) (*ResiliencyReponse, error)
	ServerStreamResiliency(*ResiliencyRequest, ResiliencyService_ServerStreamResiliencyServer) error
	ClientStreamResiliency(ResiliencyService_ClientStreamResiliencyServer) error
	BidirectionalStreamResiliency(ResiliencyService_BidirectionalStreamResiliencyServer) error
	mustEmbedUnimplementedResiliencyServiceServer()
}

// UnimplementedResiliencyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResiliencyServiceServer struct {
}

func (UnimplementedResiliencyServiceServer) UnaryResiliency(context.Context, *ResiliencyRequest) (*ResiliencyReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) ServerStreamResiliency(*ResiliencyRequest, ResiliencyService_ServerStreamResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) ClientStreamResiliency(ResiliencyService_ClientStreamResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) BidirectionalStreamResiliency(ResiliencyService_BidirectionalStreamResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) mustEmbedUnimplementedResiliencyServiceServer() {}

// UnsafeResiliencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResiliencyServiceServer will
// result in compilation errors.
type UnsafeResiliencyServiceServer interface {
	mustEmbedUnimplementedResiliencyServiceServer()
}

func RegisterResiliencyServiceServer(s grpc.ServiceRegistrar, srv ResiliencyServiceServer) {
	s.RegisterService(&ResiliencyService_ServiceDesc, srv)
}

func _ResiliencyService_UnaryResiliency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResiliencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiliencyServiceServer).UnaryResiliency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiliencyService_UnaryResiliency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiliencyServiceServer).UnaryResiliency(ctx, req.(*ResiliencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiliencyService_ServerStreamResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResiliencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResiliencyServiceServer).ServerStreamResiliency(m, &resiliencyServiceServerStreamResiliencyServer{ServerStream: stream})
}

type ResiliencyService_ServerStreamResiliencyServer interface {
	Send(*ResiliencyReponse) error
	grpc.ServerStream
}

type resiliencyServiceServerStreamResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceServerStreamResiliencyServer) Send(m *ResiliencyReponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ResiliencyService_ClientStreamResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyServiceServer).ClientStreamResiliency(&resiliencyServiceClientStreamResiliencyServer{ServerStream: stream})
}

type ResiliencyService_ClientStreamResiliencyServer interface {
	SendAndClose(*ResiliencyReponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyServiceClientStreamResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceClientStreamResiliencyServer) SendAndClose(m *ResiliencyReponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyServiceClientStreamResiliencyServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ResiliencyService_BidirectionalStreamResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyServiceServer).BidirectionalStreamResiliency(&resiliencyServiceBidirectionalStreamResiliencyServer{ServerStream: stream})
}

type ResiliencyService_BidirectionalStreamResiliencyServer interface {
	Send(*ResiliencyReponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyServiceBidirectionalStreamResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceBidirectionalStreamResiliencyServer) Send(m *ResiliencyReponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyServiceBidirectionalStreamResiliencyServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyService_ServiceDesc is the grpc.ServiceDesc for ResiliencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResiliencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resiliency.ResiliencyService",
	HandlerType: (*ResiliencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryResiliency",
			Handler:    _ResiliencyService_UnaryResiliency_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamResiliency",
			Handler:       _ResiliencyService_ServerStreamResiliency_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamResiliency",
			Handler:       _ResiliencyService_ClientStreamResiliency_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStreamResiliency",
			Handler:       _ResiliencyService_BidirectionalStreamResiliency_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/resiliency/resiliency.proto",
}
