name: Pull Request - Check Protobuf - Golang

on:
  pull_request:
    paths: 
      - 'proto/**.proto'

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: false
          cache: true

      - name: Generate Go Source Code
        shell: bash
        run: |
          make pipeline-build
      - name: Generate Go Gateway Source Code
        shell: bash
        run: |
          make pipeline-generate-gateway